[gcp_service_account]
type = """service_account"""
project_id = """automacao-eace"""
private_key_id = """bc9c4ea15435d21b3c28adaa346360721abad978"""
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDbhF4abhBb9yxr
K1aE71Cc5N6L14czMyppdXZoWgpGhSdVUpsd0v0vSNJdNhqcgJPfRMf6lQez3eIm
WfdHQ1RCGW9MG6GK+D2N1HDFmCoqp8Ay+uNR7l4Aad7vniYACF7nJSWjx/3e6zhi
oC2Vxfnp9qARvYVPaNyyNZBl1yfkcfFzTgJ+kAorL3sI5NZexwFUUN8r2BSlzPHr
qtNntntaqpx4DNoL2F8+UyYLLlLscU4w4waUoF2q6tgw5nZJZenn22OIfUZprfag
14/wTKMHCoJnirljBmxyoBQ957q8L0S3DTOcmwLAEnt1Q/s+T8HbA0MBkepg8hqN
jbNa8mPTAgMBAAECggEATFIBq7u/mVHfEiWfr5lK1DmofENDgNQVt1O9BrvjXbBW
xA3z21MrbsCpTvoMF4SGpPYTdzZQVsNaqM3XsOGiTlbsgLAMorX7JLALQ0/LvUfU
hYT/+tDewtMMTRAVkyZV5JRgOUjDpbjvQi8BmlSaNrNl5LUZP8osDROdcCL1fjFQ
YlVM4qOYFPXsW1/1k9K7DGIkI7vr9MiZa6777iGHAUGAkaUOXk9IXTf8+2kJIZVh
2RM27RBybNctH9uXv80T3LzYDw3YdgilkJJe4zxJD+vLod0YLhQE1EqITuyBEC6u
2EmnDTI55zOrGcjqKGl4zLHnPRxsE/5JCC8DXLa0BQKBgQD4y/+Ixy6lUTkAtJeF
ntEFtpELSsVZgSzHlbI3jI1q6Uc9rwcEMhDKfiOFlOTu8GqxtiTkcZKjOMuBl4Bf
mA1NhlG929NwIXJNv/tI1febMsoAi6v9vzlpM/L8/teo2LdoO5Hc8zAFLYHtmlBC
ycKLlPTtydrzbENhTyyLEm9+twKBgQDh31th2+l3fuJsz1uXHlJte9yeHU3xsA9G
E/iOlgT1VbRbDEIvZwnMqaqtoYCzeOe0NW6VF69dJTR6THl0+tlO9KHmkfmpv0Np
LvfpRVDul63NhrivNjXWmSTF15JahDl6ODBBYN0ITv7KaHK6y02Itz4txUhAMBiK
zaI1b+gnxQKBgDTWLfiARHm7XB24PI2WAtHxya/aOzsc4cOpGOYPJWFVFVoWN6k+
cK5wR17xFgVgbWg8RG13aSrcvutQn2Stx/V01xs4+hhQIhQ890KqniEJkji3cNk8
qRacf7gW7vnevGSYcgu4YbRXy8YIBY+JhZVbFwEA40za6xxZUh5e1erVAoGAfdMK
+OykleidAbhRcVF24X6KW5o/fU9ycrtVTzjK8lAX9FBT3kwr7VLmvWqmY1QK3xyU
yYE0M1MydJ59WmkS/STRu7u9tI3TY5jCibQPbZoZO9C8uP4d57nP/lYkNUBLNIZw
ezsWZjZ7QQ4GO4BdZLePb7fik783LLt4jQQV83ECgYEA6V1ynHHK/oAWZ4dlAc0H
fZ1lf2VNbBm0O7OqGtaa9Ct8AvE7RZRzsT4jPufOAXUPmLTDfBFXAeB8SdJpmEd7
hJeIa27cEhDzC6M0u8aY1pM7JnpVEjqVXj0tQQTwgIWKP90Lsronwm1WXiYWssmW
+WeowmUw6JojE11KeY1BvtQ=
-----END PRIVATE KEY-----
"""
client_email = """automacao-eace@automacao-eace.iam.gserviceaccount.com"""
client_id = """117474132211332159669"""
auth_uri = """https://accounts.google.com/o/oauth2/auth"""
token_uri = """https://oauth2.googleapis.com/token"""
auth_provider_x509_cert_url = """https://www.googleapis.com/oauth2/v1/certs"""
client_x509_cert_url = """https://www.googleapis.com/robot/v1/metadata/x509/automacao-eace%40automacao-eace.iam.gserviceaccount.com"""
universe_domain = """googleapis.com"""
