services:
  omada-exporter:
    build: .
    container_name: omada_exporter_service
    restart: unless-stopped
    shm_size: '2gb'
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 1G
        reservations:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - OMADA_CLI=true
      - OMADA_EMAIL=${OMADA_EMAIL:-noceace@bitinternet.com.br}
      - OMADA_PASSWORD=${OMADA_PASSWORD:-""}
      - OMADA_INTERVAL=${OMADA_INTERVAL:-30}
      - OMADA_DIR=/app/dados_omada
    volumes:
      - ./dados_omada:/app/dados_omada
