services:
  eace-os-exporter:
    build: .
    container_name: eace_os_exporter_robot
    restart: always
    shm_size: '2gb'
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 1G
        reservations:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - EACE_EMAIL=${EACE_EMAIL:-noc@bitinternet.com.br}
      - EACE_PASSWORD=${EACE_PASSWORD:-""}
    volumes:
      - ./dados_eace:/app/dados_eace
    command: ["python", "-u", "eace_os_exporter.py", "--intervalo", "600"]
